Jutzig/topic/csharp
jutzig/jabylon-plugins pull request #4
Opened 2019-08-15 08:58 UTC by cgrom

fix when file for new translation has to be created

2019-08-30 15:32 UTC, jutzig commented on csharp/.classpath
> +	<classpathentry exported="true" kind="lib" path="C:/Program Files/Java/jdk1.8.0_202/lib/tools.jar"/>
This is incorrect, don't push that

2019-08-30 15:36 UTC, jutzig requested changes

2019-08-30 15:36 UTC, jutzig commented on csharp/.classpath
> +	<classpathentry exported="true" kind="lib" path="C:/Program Files/Java/jdk1.8.0_202/lib/tools.jar"/>
This is incorrect, don't push that

2019-08-30 15:36 UTC, jutzig commented on csharp/src/main/java/org/jabylon/csharp/CSharpConverter.java
> +	private static final String EMPTY_RES_FILE = "<root>\r\n" +
needs to be extracted into a file

2019-08-30 15:36 UTC, jutzig commented on csharp/src/main/java/org/jabylon/csharp/CSharpConverter.java
> +		LOG.debug("C#:load0");
these debug statements are pointless.
Also, log messages do not - and should not - contain location information. When the log is written, it contains class, method, and - if wanted - line numbers

2019-08-30 15:36 UTC, jutzig commented on csharp/src/test/java/org/jabylon/csharp/CSharpConverterTest.java
> -public class CSharpConverterTest {
why would you delete the tests?

2019-08-30 15:36 UTC, jutzig commented on csharp/src/test/java/org/jabylon/csharp/CSharpScannerTest.java
> -public class CSharpScannerTest {
keep the test classes

2019-10-10 12:03 UTC, cgrom commented on csharp/src/main/java/org/jabylon/csharp/CSharpConverter.java
> +	private static final String EMPTY_RES_FILE = "<root>\r\n" +
extracted in file const.properties

2020-04-06 11:09 UTC, merged